/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatInputArea: typeof import('./src/components/SuChat/ChatInputArea.vue')['default']
    ChatRecordsArea: typeof import('./src/components/SuChat/ChatRecordsArea.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ModelSelect: typeof import('./src/components/SuChat/ModelSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuAsider: typeof import('./src/components/SuAsider/index.vue')['default']
    SuHeader: typeof import('./src/components/SuHeader/index.vue')['default']
    TextArea: typeof import('./src/components/SuChat/TextArea.vue')['default']
    ToolBar: typeof import('./src/components/SuHeader/ToolBar.vue')['default']
  }
}
